#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-fill /home/yuno/Pictures/paper2.png &
# xrandr --output HDMI1 --mode 1366x768 &
polybar &
xrdb -load ~/.config/.Xresources &
exec xinput disable 'SynPS/2 Synaptics TouchPad' &
exec xinput --set-prop "TPPS/2 IBM TrackPoint" "libinput Accel Speed" 0.99 &
picom &
brightnessctl s 15% &
xset r rate 250 40 &

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7

# Other stuff
bspc rule -a firefox border_width 0
# bspc rule -a URxvt:menu state=floating rectangle=400x200+482.5+283.5
bspc config border_width         3
bspc config window_gap           3
bspc config split_ratio          0.618
bspc config top_padding          3
bspc config bottom_padding	 3
bspc config left_padding         3
bspc config right_padding        3
bspc config normal_border_color "#1e1e1e"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#685e57"
bspc config presel_feedback_color "#1e1e1e"
bspc config focus_follows_pointer true

