#! /bin/sh
sxhkd &

feh --bg-fill ~/Downloads/paper1.jpg &

$HOME/polybar-collection/launch.sh &

pgrep -x sxhkd > /dev/null &

setxkbmap gb


bspc monitor -d 1 2 3 4 5 6 7

# Other stuff
bspc rule -a firefox border_width 0
bspc config border_width         3
bspc config window_gap           3
bspc config split_ratio          0.618
bspc config top_padding          0
bspc config bottom_padding	 3
bspc config left_padding         2
bspc config right_padding        2
bspc config normal_border_color "#1e1e1e"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#685e57"
bspc config presel_feedback_color "#1e1e1e"
bspc config focus_follows_pointer true


bspc rule -a URxvt:menu state=floating rectangle=300x100+362+334
